### ISSUE TITLE
 'int' object has no attribute 'original_matrix'

### ISSUE THREAD

**Issue by sun-ris3** [Tongzhou0101/ObfuNAS#1]
Hello,

I met this error while running the code `python main.py`.

<img width="813" alt="image" src="https://github.com/Tongzhou0101/ObfuNAS/assets/105007603/d66849d8-91fd-41a9-84e1-c2b93a9c5e93">

Based on the following definition of `mutate_spec`, it seems we don't have the `old_spec` in the function call in  "main.py", line 27.

`def mutate_spec(victim_spec, old_spec, mutation_rate=1.0):`

Can anyone help on how to solve the problem?

Thanks in advance!

**Comment by Tongzhou0101** [comment]
Thanks for pointing out the problem in the previous version.

The old_spec should be initialized to the victim_spec in this case. Please check the new version of main.py (modified line 27 and line 60).
